name: 📖 Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get source code
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.10'
        cache: "pip"
        cache-dependency-path: "requirements.txt"

    - name: Set up NodeJS (for search index prebuilding)
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt

    - name: Deploy to Github Pages
      run: |
        git config --global user.name "${{ secrets.BOT_NAME }}"
        git config --global user.email "${{ secrets.BOT_MAIL }}"
        mkdocs gh-deploy --clean --force --verbose
